### PR TITLE
support yowsup wa16 protocol and axolotol changes

### PR DESCRIPTION
**Pull request by rigid**
Since i'm not really familiar with transwhat and spectrum, this might need additional changes. I'm sending a PR because it works for me (and might be more workable than the current state) and I maybe it helps.

- encoding fixes
- enable yowsup wa16 protocol, use android env
- adapt to axolotl related API changes

### CODE REVIEW

**Comment by stv0g** [comment]
I am currently a bit busy to test this.
But maybe somebody else steps up and can test it?
I would really like to merge it.

**Comment by thundergreen** [comment]
I will test it. Hopefully my number won't get blocked after.I extracted my password out of WhatsApp so I hope it will work

**Comment by rigid** [comment]
While basic stuff works for me, there still are issues with transwhat and yowsup:
- i needed https://github.com/tgalal/yowsup/pull/1561 to get it running
- contacts soon appear offline in buddylist (but appear online when they write again) maybe related to https://github.com/tgalal/yowsup/issues/1555
- received files don't get decrypted

and probably a lot more. But I hope, that a usable version enables others to contribute by fixing stuff.

**Comment by thundergreen** [comment]
Does transwhat still work ?

**Comment by stv0g** [comment]
I had not the chance to fully test this PR.
However there is a user which reported that this PR works for him.

Currently there is no reason why it should not work.
But there might be some minor bugs in the source code atm.

More testers are welcome.

**Pull request merged**
